### PR TITLE
Issue #62 fix example apps

### PR DESCRIPTION
**Pull request by ebebbington**
Fixes #63 

**Description**

* Fixed compilation errors for chat and tls app

**Other Notes**

* Unable to test the tls app actually works due to bad cert error on the client - i need to ask how this works because it's never worked for us (tls that is)

**_From Eric: This moves the example_apps dir to tests/integration_wip. The example apps will be integration tests. Examples of applications will now live in the documentation._**

### CODE REVIEW

**Comment by ebebbington** [comment]
Going to make sure the chat app works after updating the. drash dep to v1.x

**Comment by ebebbington** [comment]
Yeah, just had to pull @crookse latest changes and use the fix in the latest release for drash (1.1.1)
